### ISSUE TITLE
Incorrect parameters load when SendGrid step is added

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-sendgrid#12]
Below are the current fields that loan when SendGrid step is added:

api_user <--- incorrect
api_key <-- incorrect
subject
from
fromname <-- not needed
bcc
text
html

![screen shot 2015-03-26 at 5 03 19 pm](https://cloud.githubusercontent.com/assets/8238417/6858127/1d06639e-d3da-11e4-8041-dd20318b44a9.png)

Here is the minimum / necessary fields to send a message w/sendgrid

apiuser 
apikey
from
lead.email -- needs to just be email
subject
text

cc and bcc are optional

![screen shot 2015-03-26 at 5 07 26 pm](https://cloud.githubusercontent.com/assets/8238417/6858191/a4009f5e-d3da-11e4-9420-41f5bc811646.png)

**Comment by cgrayson** [comment]
Why do you say that `api_user` and `api_key` should be `apiuser` and `apikey`? 

Not everything in that default list of what _can_ be mapped, _must_ be mapped. If you don't want to use BCC, or "from name" (a human-readable, non-email-address version of "from"), or whatever, then delete those mappings. 

The "email"/"to" parameter is called `lead.email` so that it will automatically use the lead's `email` value, though of course that can be changed if you add a mapping.

**Comment by kcaponeAP** [comment]
oh my bad it's fixed. so it works with both api_user and apiuser. 

Can we concentrate on just fixing the field ```lead.email```regular ole ```email``` doesn't work

**Comment by alexkwolfe** [comment]
@kcaponeAP, did you read Chris' comment about the `lead.email` field?

**Comment by kcaponeAP** [comment]
@alexkwolfe yes, thank you. Read the comment about lead.email. I think what's clear is that I'm using the sendgrid step for another use here. I'm alerting a user (support@activeprospect.com) when there is a user.

I can see clearly that this step might be used to send a followup email to the email address attached to the lead.

**Comment by zalary** [comment]
what else do you need here?  is something not working with the mapping that Chris suggested?

**Comment by poppop51** [comment]
I think K. is clear and OK now on the "apikey" vs "api_key" item, but the mapping popup's instructions do use "apikey" while the right-hand mapping column displays "api_key". Possibly confusing for the user.

Re the email item: There's not a functional issue here, but an there is an ergonomic/UI one.
The mappings popup defaults the "to:" recipient to the lead email but does not present that fact to the user. There's nothing readily visible to tell the user where the email will be sent, which is obviously a basic, critical piece of information.
The UI needs to show the user what the default is and at least give them a clue how to designate a different 'to:' recipient.

Additionally, I did find one functional UI problem in the mapping popup: When I make a change in the mapping but click "Cancel" instead of "OK" my changes are saved anyway. They shoudl only be saved if I click "OK".

Finally, for the with list: If certain mappings are required and other optional, those facts should be readily and specifically apparent in the mapping popup itself.

**Comment by zalary** [comment]
cool.  in that case, I will close this and reference [#487 on the leadconduit-client repo](https://github.com/activeprospect/leadconduit-client/issues/487).

there are some planned updates to the sendgrid integration(s) that will help but most of these are UI clarity issues and not something to be fixed on this integration.

**Comment by cgrayson** [comment]
> I think K. is clear and OK now on the "apikey" vs "api_key" item, but the mapping popup's instructions do use "apikey" while the right-hand mapping column displays "api_key". Possibly confusing for the user.

It took me a few minutes to figure out what you meant. The text at the top is boilerplate that has nothing to do with this particular integration. 


> The UI needs to show the user what the default is and at least give them a clue how to designate a different 'to:' recipient.

Excellent point; noted in client issue 487, which Zal linked to. Showing optional & required is also noted there. 

> Additionally, I did find one functional UI problem in the mapping popup: When I make a change in the mapping but click "Cancel" instead of "OK" my changes are saved anyway. They shoudl only be saved if I click "OK".

I think I see what you mean. I'll open a client UI issue for this.
